Repository kkrt-labs/go-utils, pull requests merged in 2025-03, with the labels that each got.

#15 📝 Fix typo in `CONTRIBUTING.md`
  CONTRIBUTING.md
Labels: non-breaking-change, type.docs

#14 ✏️ Fix typos in code docstring
  jsonrpc/websocket/client.go
  websocket/client.go
Labels: non-breaking-change, type.chore

#24 ✨ Extend configurability for logging
  log/README.md
  log/config.go
  log/config_test.go
  log/flags.go
  log/flags_test.go
  log/logger.go
Labels: non-breaking-change, type.feat

#27 💚 Fix CI test workflow trigger
  .github/workflows/test.yml
Labels: type.devops, non-breaking-change

#29 🐛 Add missing fields to log configuration
  log/README.md
  log/config.go
  log/config_test.go
  log/flags.go
  log/flags_test.go
  spf13/flags.go
Labels: non-breaking-change, type.chore, type.fix

#36 ✨ Add utilities for managing an HTTP Server
  net/entrypoint.go
  net/entrypoint_test.go
  net/http/server.go
  net/http/server_test.go
Labels: non-breaking-change, type.feat, type.feature

#37 ✨ Expose net.Listener.Addr on Server
  net/http/server.go
  net/http/server_test.go
Labels: non-breaking-change, type.feat, type.feature

#39 ⬆️ Bump Golang to 1.24.1
  .github/workflows/test.yml
  Makefile
  go.mod
Labels: non-breaking-change, type.chore

#40 🍱 Add package app to manage efficient app lifecycle
  app/README.md
  app/app.go
  app/app_test.go
  app/config.go
  app/flags.go
  app/flags_test.go
  app/options.go
  app/svc/interface.go
  app/svc/tag.go
  app/svc/tag_test.go
  ethereum/rpc/instrument.go
  ethereum/rpc/instrument_test.go
  ethereum/rpc/jsonrpc/client_test.go
  examples/app/main.go
  go.mod
  go.sum
  gomock/matchers.go
  jsonrpc/client.go
  jsonrpc/decorator.go
  jsonrpc/http/client_test.go
  jsonrpc/instrumentation.go
  jsonrpc/instrumentation_test.go
  jsonrpc/logging.go
  jsonrpc/mock/client.go
  log/README.md
  net/entrypoint.go
  net/entrypoint_test.go
  net/http/config.go
  net/http/entrypoint.go
  net/http/entrypoint_test.go
  net/http/server.go
  net/http/server_test.go
  net/http/testutils/gock.go
  store/instrument.go
  store/instrument_test.go
  store/mock/store.go
  store/multi/store_test.go
  store/store.go
  svc/service.go
  tag/testutils.go
  tag/value.go
Labels: non-breaking-change, type.feat, type.feature

#43 🎨 Improve store package
  store/compress/config.go
  store/compress/store.go
  store/compress/store_test.go
  store/file/config.go
  store/file/store.go
  store/file/store_test.go
  store/instrument.go
  store/instrument_test.go
  store/memory/store.go
  store/memory/store_test.go
  store/mock/store.go
  store/multi/config.go
  store/multi/store.go
  store/multi/store_test.go
  store/s3/config.go
  store/s3/store.go
  store/store.go
Labels: non-breaking-change, type.chore

#48 🐛 Fix file store to not error on creation if data directory does not exist
  store/file/store.go
  store/file/store_test.go
Labels: non-breaking-change, type.fix

#49 🔊 Make jsonrpc timeouts and retries more explicit
  jsonrpc/decorator.go
  jsonrpc/decorator_test.go
Labels: non-breaking-change, type.chore
