Repository kkrt-labs/go-utils, pull requests merged in 2025-02, with the labels that each got.

#4 💚 Update upload-artifact action version
  .github/workflows/test.yml
Labels: type.devops, non-breaking-change

#5 ✨ Add HTTP client for EthProofs API
  ethproofs/README.md
  ethproofs/client/client.go
  ethproofs/client/http/aws.go
  ethproofs/client/http/aws_test.go
  ethproofs/client/http/client.go
  ethproofs/client/http/clusters.go
  ethproofs/client/http/clusters_test.go
  ethproofs/client/http/config.go
  ethproofs/client/http/machine.go
  ethproofs/client/http/machine_test.go
  ethproofs/client/http/proofs.go
  ethproofs/client/http/proofs_test.go
  ethproofs/client/mock/client.go
  example/ethproofs/main.go
Labels: non-breaking-change, type.feat, type.feature

#6 ✨ Create HTTP client for Herodotus Atlantic API
  examples/herodotus/atlantic/fibonacci_pie.zip
  examples/herodotus/atlantic/main.go
  herodotus/atlantic/README.md
  herodotus/atlantic/client/client.go
  herodotus/atlantic/client/http/client.go
  herodotus/atlantic/client/http/config.go
  herodotus/atlantic/client/http/generate_proof.go
  herodotus/atlantic/client/http/generate_proof_test.go
  herodotus/atlantic/client/http/get_proof.go
  herodotus/atlantic/client/http/get_proof_test.go
  herodotus/atlantic/client/http/list_proofs.go
  herodotus/atlantic/client/http/list_proofs_test.go
  herodotus/atlantic/client/mock/client.go
Labels: non-breaking-change, type.feat

#7 ✨ Add stores to File, and AWS S3
  aws/config.go
  ethproofs/client/mock/client.go
  go.mod
  go.sum
  store/compress/config.go
  store/compress/store.go
  store/compress/store_test.go
  store/file/config.go
  store/file/store.go
  store/file/store_test.go
  store/mocks/mockstore.go
  store/multi/config.go
  store/multi/store.go
  store/multi/store_test.go
  store/s3/config.go
  store/s3/store.go
  store/store.go
Labels: non-breaking-change, type.feat

#12 fix: typos in documentation files
  CONTRIBUTING.md
  tag/set.go
Labels: non-breaking-change, type.docs
