Repository kkrt-labs/go-utils, pull requests merged in 2025-04, with the labels that each got.

#62 🎨 Extend App and Log configuration for compatibility with AWS CDK
  app/app.go
  app/app_test.go
  app/config.go
  app/config_test.go
  app/flags.go
  app/flags_test.go
  common/ptr.go
  common/ptr_test.go
  config/decode_hook.go
  config/encode_hooks.go
  config/inspector.go
  config/inspector_test.go
  config/spf13.go
  config/viper.go
  config/viper_test.go
  examples/app/main.go
  log/config.go
  log/config_test.go
  log/flags.go
  log/flags_test.go
  net/http/config.go
  net/http/config_test.go
  net/http/entrypoint.go
Labels: non-breaking-change, type.chore

#56 📚 fixed broken link
  ethproofs/README.md
Labels: non-breaking-change, type.docs

#64 💄 Clean app configuration flags usage guidelines
  app/config.go
  app/config_test.go
Labels: non-breaking-change, type.fix

#65 ✨ Add a skip tag value for config tag inspection
  config/encode_hooks.go
  config/inspector.go
  config/viper.go
  config/viper_examples_test.go
  config/viper_test.go
Labels: non-breaking-change, type.chore

#71 🎨 Update store key management
  herodotus/atlantic/client/mock/client.go
  store/compress/store.go
  store/compress/store_test.go
  store/file/store.go
  store/file/store_test.go
  store/helpers.go
  store/helpers_test.go
  store/instrument.go
  store/instrument_test.go
  store/memory/store.go
  store/memory/store_test.go
  store/mock/store.go
  store/multi/store.go
  store/multi/store_test.go
  store/s3/store.go
  store/store.go
Labels: non-breaking-change, type.chore

#73 ✅ Add unit tests for S3 store
  aws/mock/s3.go
  aws/s3.go
  aws/s3_test.go
  store/s3/store.go
  store/s3/store_test.go
Labels: non-breaking-change, type.test

#75 🎨 Extend store/compress with Delete and Copy methods
  store/compress/store.go
  store/compress/store_test.go
  store/file/store_test.go
  store/memory/store_test.go
  store/mock/store_test.go
  store/multi/store_test.go
  store/s3/store_test.go
Labels: non-breaking-change, type.chore, type.fix

#76 ✨ Add a NoOp store
  store/content_encoding.go
  store/content_type.go
  store/noop.go
  store/noop_test.go
  store/store.go
Labels: non-breaking-change, type.chore

#78 🐛 Fix store multi to not return in case of nil
  store/multi/store.go
Labels: non-breaking-change, type.fix
